spring:
  thymeleaf:
    cache: true
  data:
    mongodb:
      uri: ${MONGODB_URI}

facebook:
  client:
    clientId: ${FACEBOOK_CLIENT_ID}
    clientSecret: ${FACEBOOK_CLIENT_SECRET}

google:
  client:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}